### ISSUE TITLE
ticket claiming

### ISSUE THREAD

**Issue by mcmeeshi** [nickyhajal/wds-reflect#1]
Hi Nicky. I just tested the ticket purchase/claiming process on my phone. I answered "yes" that I had been to WDS before and entered my previously used e-mail and password without a problem. I then purchased three tickets. There was just one little thing where the next screen I saw showed the bottom half of the ticket claim form, the part with the text boxes, so I had to scroll up to see the instructions at the top.

I claimed one of the tickets for myself and when it asked for my e-mail address, this time I put in a different e-mail and made my first name "Micheel". Just wondering: Is my old account still linked to my new purchase and which name will the system use for me?

Something I noticed when I went to enter the name and e-mail for my second ticket is that the form was telling me "Ticket 3 of 6" - so it appeared that I had purchased 6 tickets. But maybe that's from a previous fake transaction I had done months ago?

I received my receipt, "ticket was assigned" notices, and "you're going to WDS" e-mails no problem.

Great job.

Michelle

**Comment by ibwatson** [comment]
I also had this issue once I was logged into the hub, so yes, it's pulling any previous test transactions and aggregating them :)
