### ISSUE TITLE
iOS 10 Ticket Purchase: Virtual Keyboard

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#10]
There are a few issues where tapping a button while the virtual keyboard is shown on-screen results in some weird shifting of the page and process indicators:

![img_6976](https://cloud.githubusercontent.com/assets/7308599/22894126/cae250a6-f1cc-11e6-9ac7-f8cbaad0733c.PNG)

![img_6977](https://cloud.githubusercontent.com/assets/7308599/22894160/e6c9f72e-f1cc-11e6-8267-eddc808a0492.PNG)

**Comment by nickyhajal** [comment]
What button?

**Comment by nickyhajal** [comment]
Ah - the virtual enter button?

**Comment by ibwatson** [comment]
I hit enter on my keyboard after typing the address instead of clicking on the Save & Continue button. Not sure if that makes any difference. Was just the only thing different about how I normally do it.

-- 
Isaac B Watson
Kickass Conferences, LLC
(Creative conference design and production services)
503.944.9271

Website: ibwatson.com
 <http://ibwatson.com/>Twitter: @ibwatson <http://twitter.com/ibwatson>
Instagram: @ibwatsongram <http://instagram.com/ibwatsongram>

**Comment by ibwatson** [comment]
Sorry, I confused the threads here. I hit the virtual enter button on the virtual keyboard to virtually complete my virtual purchase and fill out my virtual profile. :) It dismisses the keyboard but keeps the same scroll position as when the keyboard's there.
