### ISSUE TITLE
iOS Profile Setup: Interests column width

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#12]
Interest boxes are stretching across the screen bounds and bleeding onto the Continue button.

![img_6980](https://cloud.githubusercontent.com/assets/7308599/22894252/2dadab18-f1cd-11e6-811c-fda0a064b0f9.PNG)

**Comment by ibwatson** [comment]
Still seeing this in the latest push and live testing.

**Comment by nickyhajal** [comment]
Should be fixed
