### ISSUE TITLE
Profile Setup: Interest Selection

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#14]
Hover color for boxes is fire engine red. Can we change to the light blue brand color or one of the others from our palette? (Safari)

![screen shot 2017-02-14 at 4 06 51 pm](https://cloud.githubusercontent.com/assets/7308599/22955206/b1fc559c-f2cf-11e6-8469-25b36aec81e3.png)

**Comment by nickyhajal** [comment]
It's red to signify deleting an interest - this is the error/delete red that was from the old site palette.

Happy to change it - but there's not a similar red in our current palette to communicate that you're removing an interest.

**Comment by ibwatson** [comment]
Oh duh. I didn't realize I was hovering over the ones I'd already selected. How about #B64025 instead? That's an auxiliary red we've used in a few things.

**Comment by nickyhajal** [comment]
holla
