### ISSUE TITLE
Profile Setup: Image Upload

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#18]
The auto-center and auto-crop function is behaving strangely with a photo I took with my iPhone, whether uploaded from mobile or desktop. It seems to be zooming way in on the center, making it completely unreadable. See screen shot and source photo for comparison. (Pardon the butts)

![screen shot 2017-02-14 at 4 36 23 pm](https://cloud.githubusercontent.com/assets/7308599/22955990/16b5fe62-f2d4-11e6-9069-7caf9d57dc5a.png)

![img_7021](https://cloud.githubusercontent.com/assets/7308599/22955992/1cc521b6-f2d4-11e6-8e75-005145745608.JPG)

**Comment by nickyhajal** [comment]
I *think* I may have this doing face detection to improve cropping... so in this case that may be confusing things... I may have to look to see if I can find a good butt-detection algorithm.

thread of the year btw

**Comment by ibwatson** [comment]
Ha! This is choice. Shall I try with an actual face photo instead?

**Comment by ibwatson** [comment]
Hmmm, it's also not catching the rotation metadata, and definitely not detecting my face. :)

![img_7022](https://cloud.githubusercontent.com/assets/7308599/22956323/3881fe68-f2d6-11e6-96f1-ba81c84650a2.PNG)

**Comment by ibwatson** [comment]
Unless now my nose reads as a butt.

**Comment by nickyhajal** [comment]
hm weird - can you attach the original pic

**Comment by ibwatson** [comment]
It didn't save that image to my camera roll since I took it on the fly, but here's one of several I tried uploading from photos in my camera roll, same issue with the rotation. I ended up AirDroping the image to my computer then using Preview to rotate 90º and back again, then saving the file before uploading it through Safari as seen in the first screenshot in the thread.

![img_7019](https://cloud.githubusercontent.com/assets/7308599/22957385/ce053b02-f2dc-11e6-87ca-58a647b8de3d.JPG)

**Comment by ibwatson** [comment]
That photo reads as portrait on iOS and macOS (something I've seen occur many times in the past with image uploads)
