### ISSUE TITLE
Foundation featured slider glitch

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#2]
Low priority: the line in between the dots on this module doesn't run all the way through. Safari 10.0.2 on macOS Sierra
![screen shot 2017-02-12 at 7 51 11 pm](https://cloud.githubusercontent.com/assets/7308599/22870516/c4434ae0-f15c-11e6-8980-5b124da846df.png)

**Comment by nickyhajal** [comment]
Should be fixed in staging
