### ISSUE TITLE
Mobile for Android

### ISSUE THREAD

**Issue by wkorenek** [nickyhajal/wds-reflect#21]
![screenshot_2017-02-14-16-46-59](https://cloud.githubusercontent.com/assets/19242763/22956715/762e0d2c-f2d8-11e6-9c0d-286803340a10.png)
![screenshot_2017-02-14-16-47-30](https://cloud.githubusercontent.com/assets/19242763/22956714/762c1d50-f2d8-11e6-82c5-20f845a3d866.png)

**Comment by nickyhajal** [comment]
Gunna close this just because we have these issues in other threads!
