### ISSUE TITLE
Live site ticket claiming 

### ISSUE THREAD

**Issue by mcmeeshi** [nickyhajal/wds-reflect#22]
Not sure how big an issue this is. I went to the live site and purchased 3 tickets via my iPhone. I claimed one for my fake self, and one for fake Jedd. I left the third empty and closed the Chrome app. While waiting for my e-mail confirmation, I reopened Chrome and the site was asking me again if one of the tickets was for myself. I clicked yes and I guess that means I accidentally claimed two of my three tickets for myself. When I got the confirmation e-mails a few minutes later, I tried clicking on the link in the receipt e-mail and it said that I had already claimed three tickets. 

I went through the profile set up process, which was very smooth. Only thing is that the dispatch looked a little wonky on my iPhone, with some of the text trailing off beyond the screen instead of wrapping. (And maybe I shouldn't have posted a comment from my fake account - oops!)

**Comment by nickyhajal** [comment]
Thanks for this feedback Michelle! These issues should be resolved! :)
