### ISSUE TITLE
Profile Setup: ticket purchase transition

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#3]
I tested purchasing a 6th ticket, and after it was successful and I assigned the ticket, it automatically took me to my own original purchase profile setup. The transition there was a little awkward, since it just switched over to the original name I provided without any context. This could be confusing to people buying tickets for friends who haven't set up their own profile yet.

**Comment by nickyhajal** [comment]
So - are you saying that since you already setup your ticket, you should go be taken to the hub instead?

**Comment by ibwatson** [comment]
I don't think it needs to go straight to the hub. It just confused me for a minute because I was assigning the ticket to someone, then it went straight into my own profile setup. This is probably an edge case, but I was thinking the best solution would be to either add a conditional message in those instances that says, "Great! Now that you've assigned that ticket, let's have you set up your own profile." or something like that. Or maybe even a modal that says "Ticket assigned! Would you like to set up your own WDS profile now?" With a Yes or Later option. Maybe that's too complicated.
