### ISSUE TITLE
Attendee schedules: rsvps not showing up on the online hub page

### ISSUE THREAD

**Issue by jeddc** [nickyhajal/wds-reflect#31]
Attendee Michael Feerer (user ID: 10613) is signed up for a lot of events. However it's not displaying in his personalized Hub schedule. It is posting in the app and I see all the rsvps in the backend:

<img width="992" alt="screen shot 2018-06-15 at 1 38 56 pm" src="https://user-images.githubusercontent.com/11277509/41488587-ade7916e-70a1-11e8-9781-76e705098e41.png">

But not on the front end:

<img width="832" alt="screen shot 2018-06-15 at 1 41 01 pm" src="https://user-images.githubusercontent.com/11277509/41488610-c793a94a-70a1-11e8-8b08-26264b50d1f5.png">

**Comment by nickyhajal** [comment]
Should be fixed :)
