### ISSUE TITLE
Profile Setup: Country List

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#5]
Countries drop-down are ordered strangely... seems to be alpha by country abbreviation, not first letter of country name (ex: ZA for South Africa listed with Zs instead of with Ss)

![screen shot 2017-02-13 at 8 35 39 am](https://cloud.githubusercontent.com/assets/7308599/22893601/fa57fdba-f1ca-11e6-96d8-b3e73b7909d5.png)

**Comment by nickyhajal** [comment]
Will be fixed in next push!
