### ISSUE TITLE
Profile Setup: Twitter Auth

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#6]
Seems to be broken. I'm taken to the login screen with Twitter, but then the actual api.worlddominationsummit.com authorization hangs for several minutes, then ultimately returns the "Oops! Looks like the WDS site is off on a short adventure!" error screen.

![screen shot 2017-02-13 at 8 38 12 am](https://cloud.githubusercontent.com/assets/7308599/22893652/28a0b3c4-f1cb-11e6-940f-08795fa53726.png)

**Comment by nickyhajal** [comment]
I believe this is an issue related to being in staging and the callback going to the live site (where the staging user doesn't exist)

Let's test this shortly on the live site
