### ISSUE TITLE
Profile Setup: Photo Upload

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#7]
When uploading a photo, the WDS globe appears cropped oddly, and the uploaded photo does not display, whether clicked to file browser or dragged to upload. Can we also add size guidelines (pixel dimensions or a max file size)?

![screen shot 2017-02-13 at 8 39 22 am](https://cloud.githubusercontent.com/assets/7308599/22893709/624ab37c-f1cb-11e6-9ce2-a6cfe705da30.png)

**Comment by nickyhajal** [comment]
This is also a staging/production issue that seems to work fine in production for me. There isn't really a dimension/size constraint - the server resizes and crops to the center.
