### ISSUE TITLE
Profile Setup: Let people know/hub

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-reflect#9]
Is there supposed to be a social share option on this screen? Also, this may just not be ready yet, but clicking the hub link returns the new 404 page.

![screen shot 2017-02-13 at 8 42 42 am](https://cloud.githubusercontent.com/assets/7308599/22893823/bbba10ba-f1cb-11e6-9950-331d87803374.png)

**Comment by nickyhajal** [comment]
Should be fixed in next push!
